[package]
name = "textpad"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.14.1"
toml = "0.5.8"
rfd = "0.14.0"
[build-dependencies]
slint-build = "1.14.1"

[profile.release]
out-dir = "C:\\Users\\Administrator\\Desktop\\icons"